src/App.vue, src/components/InputSelector/InputSelector.vue, src/components/Loader/Loader.vue, src/components/MultiPart/MultiPart.vue, src/components/MultiPart/index.js, src/components/Survey/Survey.vue, src/components/SurveyItem/SurveyItem.vue
not all of the widgets of the multipart are implemented, but basic functionality is there.
=> Multipart functionality

.bitmap, src/App.vue, src/components/Inputs/WebAudioRecord/Audio.vue
Here is a version where the responses are saved as blobs.
=> Blobbed audio

.bitmap, src/components/MultiPart/MultiPart.vue, src/components/SurveyItem/SurveyItem.vue
=> Multipart restart

src/App.vue, src/components/Survey/Survey.vue
& will checkout dropdowns next
=> Adding variable maps & disabling debug

src/components/InputSelector/InputSelector.vue, src/components/Inputs/WebFloatInput/FloatInput.vue, src/components/Inputs/WebFloatInput/index.js
See issue #18 
Created a new input type called FloatInput that actually checks if the input is a finite number.
=> [WIP] add a new input type for finite number (ints or floats)

README.md
tiny changes to the URL of the app in the README
=> minor update on the README

src/App.vue, src/components/Survey/Survey.vue
=> enh:client side branching logic at protocol level

src/components/InputSelector/InputSelector.vue, src/components/Inputs/TextArea/TextArea.vue, src/components/Inputs/TextArea/index.js
=> new component: textarea

src/components/Inputs/SliderInput/SliderInput.vue, src/locales/en.json, src/locales/es.json
fixes #247 , #254 and https://github.com/ReproNim/reproschema-library/issues/59
=> refactor export and next button and slider component

src/components/Inputs/SliderInput/SliderInput.vue
=> remove disable on slider submit button

src/components/Inputs/WebRadio/Radio.vue
closes #278
@danielmlow -  could you please check if this looks better to you
=> increasing line height in the radio input type

src/components/InputSelector/InputSelector.vue, src/components/Inputs/WebAudioRecord/Audio.vue
@alishakodibagkar wanted to have `AudioRecord` input but without option to stop earlier
=> adding to AudioRecord a new mode: audioRecorNoStop 

src/router/index.js
Edit to reproschema-ui/src/router/index.js: 
If the URL contains "auth_token" or "uid", all parameters in the URL query will be pushed between activities
=> connect URL query parameters btw activities

src/components/InputSelector/InputSelector.vue, src/components/Inputs/RangeInput/RangeInput.vue, src/components/Inputs/RangeInput/index.js
This is in part relates to #156 to deal to provide ways to muliple numerical answers for one item.
This specifically deals with a range response that takes 2 floats inputs and ensure that the second one is greater than the first.
=> [ENH] adds a range input type

src/App.vue, src/components/InputSelector/InputSelector.vue, src/components/Inputs/StaticReadOnly/StaticReadOnly.vue, src/config.js
opening a PR so that we can review the changes, and make fixes as needed.
=> fix: temporary fix for static

.codespellrc, .github/workflows/codespell.yml, src/App.vue, src/components/Landing/Landing.vue
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
reproschema-py already has it
=> Add codespell support (config, workflow to detect/not fix) and make it fix few typos

src/components/Survey/Survey.vue
in this part of the ui only one substition is made. this fixes it.
=> fix: replace all occurrances of match in survey

.github/workflows/build_deploy.yml, README.md, package-lock.json, src/App.vue, src/components/Landing/Landing.vue, src/components/Section/Section.vue, src/components/StudyIntroduction/StudyIntroduction.vue, src/components/Survey/Survey.vue, src/router/index.js
adjusts node to 23.x
- change router handling for redirect to same page
- keeping query parameters when changing location
- fix expiry time evaluation
- adjust ui version in result reporting
=> Addresses various fixes and enhancements

src/App.vue, src/components/Landing/Landing.vue, src/components/StudyIntroduction/StudyIntroduction.vue, src/components/Survey/Survey.vue
clean up how query parameter is passed along.
=> ref: clean up query parameter setting

src/components/Section/Section.vue
this allows skip or don't know properties to be evaluated inside sections. cc: @ibevers
=> fix: add properties to section activity
